apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: order-service
          image: app/tc-order-service:latest
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
          env:
            - name: ENVIRONMENT
              value: "production"
