apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:1.0.0
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
            limits:
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: order-service-config
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-file
          configMap:
            name: order-service-config
